[AIRFLOW-1039] Raise AirflowError when two concurrent processes are trying to create duplicate entries in dag_run table.
When Two concurrent processes are trying to trigger the same dag with the same execution date at the same time, the IntegrityError is thrown by SQLAlchemy:

IntegrityError: (_mysql_exceptions.IntegrityError) (1062, "Duplicate entry 'poc_dag2-2017-03-24 07:21:22.000000' for key 'dag_id'") [SQL: u'INSERT INTO dag_run (dag_id, execution_date, start_date, end_date, state, run_id, external_trigger, conf) VALUES (%s, %s, now(), %s, %s, %s, %s, %s)'] [parameters: ('poc_dag2', datetime.datetime(2017, 3, 24, 7, 21, 22), None, u'running', '284711d4-109d-11e7-a4aa-005056bc55dd', 1, '\x80\x02}q\x01X\x0b\x00\x00\x00input_files]q\x02X>\x00\x00\x00/homeb/d56032/dev/airflowtest/input2/data15:21:21.845102000.gzq\x03as.')]

This is not consistent with AirflowException returned by trigger_dag() function. Moreover, the session is not rolled back, hence also another exception is occurring:

InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.IntegrityError) (1062, "Duplicate entry 'poc_dag2-2017-03-24 06:35:15.000000' for key 'dag_id'") [SQL: u'INSERT INTO dag_run (dag_id, execution_date, start_date, end_date, state, run_id, external_trigger, conf) VALUES (%s, %s, now(), %s, %s, %s, %s, %s)'] [parameters: ('poc_dag2', datetime.datetime(2017, 3, 24, 6, 35, 15), None, u'running', 'b6f3e9ae-1096-11e7-9cea-005056bc55dd', 1, '\x80\x02}q\x01X\x0b\x00\x00\x00input_files]q\x02X>\x00\x00\x00/homeb/d56032/dev/airflowtest/input2/data14:35:13.068563100.gzq\x03as.')]