Fix very rare test_fast_follow failure.
There is an occasional (VERY RARE) case where this test failed when lambda was without delay
This problem resulted with psutil.wait() behaviour which returns None in case the process
that we wait for already exited. Psutil does not have any more information about the process
Nor cannot get the return code so it returns None which results in
`State of this instance has been externally set to success. Terminating instance.` from heartbeat
this breaks the flow of processing for that test. That's why we added small timeout to decrease
the likelihood of the race condition.

The error manifested itself with:

```
  tests/jobs/test_local_task_job.py:704:
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

  self = <tests.jobs.test_local_task_job.TestLocalTaskJob object at 0x7f9ba8376750>
  dag_run = <DagRun test_dagrun_fast_follow @ 2021-10-13 05:32:21.521590+00:00: test_dagrun_fast_follow, externally triggered: False>
  ti_state_mapping = {'A': <TaskInstanceState.SUCCESS: 'success'>, 'B': <TaskInstanceState.SCHEDULED: 'scheduled'>, 'C': None}
  error_message = 'A -> B -> C, with fast-follow ON when A runs, B should be QUEUED. Same for B and C.'

      def validate_ti_states(self, dag_run, ti_state_mapping, error_message):
          for task_id, expected_state in ti_state_mapping.items():
              task_instance = dag_run.get_task_instance(task_id=task_id)
              task_instance.refresh_from_db()
  >           assert task_instance.state == expected_state, error_message
  E           AssertionError: A -> B -> C, with fast-follow ON when A runs, B should be QUEUED. Same for B and C.
  E           assert None == <TaskInstanceState.SCHEDULED: 'scheduled'>
  E            +  where None = <TaskInstance: test_dagrun_fast_follow.B test_dagrun_fast_follow [None]>.state

  tests/jobs/test_local_task_job.py:94: AssertionError
  ---------------------------- Captured stdout setup -----------------------------
  [2021-10-13 05:32:21,463] {dagbag.py:500} INFO - Filling up the DagBag from /dev/null
  ------------------------------ Captured log setup ------------------------------
  INFO     airflow.models.dagbag.DagBag:dagbag.py:500 Filling up the DagBag from /dev/null
  ----------------------------- Captured stdout call -----------------------------
  [2021-10-13 05:32:21,499] {dag.py:2389} INFO - Sync 1 DAGs
  [2021-10-13 05:32:21,504] {dag.py:2408} INFO - Creating ORM DAG for test_dagrun_fast_follow
  [2021-10-13 05:32:21,509] {dag.py:2914} INFO - Setting next_dagrun for test_dagrun_fast_follow to 2016-01-01T00:00:00+00:00
  Running <TaskInstance: test_dagrun_fast_follow.A test_dagrun_fast_follow [running]> on host f6d28748e57e
  [2021-10-13 05:32:22,784] {local_task_job.py:212} WARNING - State of this instance has been externally set to success. Terminating instance.
  ------------------------------ Captured log call -------------------------------
  INFO     airflow.models.dag:dag.py:2389 Sync 1 DAGs
  INFO     airflow.models.dag:dag.py:2408 Creating ORM DAG for test_dagrun_fast_follow
  INFO     airflow.models.dag:dag.py:2914 Setting next_dagrun for test_dagrun_fast_follow to 2016-01-01T00:00:00+00:00
  WARNING  airflow.jobs.local_task_job.LocalTaskJob:local_task_job.py:212 State of this instance has been externally set to success. Terminating instance.
``