REST API: Fix wrong plugin schema
We serialize some plugin's fields as dictionaries leading to errors
when accessing the `/plugins` endpoint.

Here's the error:
ValueError: dictionary update sequence element #0 has length 1; 2 is required

The fields are lists of strings and this PR addresses it.