fix cli to work with celery4 and python3
loglevel  is required

[2016-12-01 16:35:07,414: CRITICAL/MainProcess] Unrecoverable error: TypeError('unorderable types: NoneType() <= int()',)
Traceback (most recent call last):
  File "/Users/roberto/.virtualenvs/stairflow/lib/python3.5/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/Users/roberto/.virtualenvs/stairflow/lib/python3.5/site-packages/celery/bootsteps.py", line 115, in start
    self.on_start()
  File "/Users/roberto/.virtualenvs/stairflow/lib/python3.5/site-packages/celery/apps/worker.py", line 143, in on_start
    self.emit_banner()
  File "/Users/roberto/.virtualenvs/stairflow/lib/python3.5/site-packages/celery/apps/worker.py", line 159, in emit_banner
    string(self.colored.reset(self.extra_info() or '')),
  File "/Users/roberto/.virtualenvs/stairflow/lib/python3.5/site-packages/celery/apps/worker.py", line 188, in extra_info
    if self.loglevel <= logging.INFO:
TypeError: unorderable types: NoneType() <= int()