Remove invalid rds waiter for db_instance and db_cluster
According to the boto3 documentation (https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/rds.html#waiters) only the following waiters are available:

* DBClusterAvailable
* DBClusterDeleted
* DBInstanceAvailable
* DBInstanceDeleted

For clusters and instances. The "stopped" target_state generate an error:

  File "/usr/local/airflow/.local/lib/python3.11/site-packages/botocore/client.py", line 1267, in get_waiter
    raise ValueError(f"Waiter does not exist: {waiter_name}")
ValueError: Waiter does not exist: db_instance_stopped