[AIRFLOW-3694] Add README.md to the Dockerfile
The README.md is being read by setup.py
and needs to be added to the Dockerfile as well.

Bug introduced in:
https://github.com/apache/airflow/pull/4503

Obtaining file:///opt/airflow
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/opt/airflow/setup.py", line 38, in <module>
        with io.open('README.md', encoding='utf-8') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'