[AIRFLOW-2536] docs about how to deal with airflow initdb failure
Add docs to faq.rst to talk about how to deal with
Exception: Global variable explicit_defaults_for_timestamp needs to be on (1) for mysql