Fix failing main
Test was failing here: https://github.com/apache/airflow/actions/runs/11482958870/job/31957874656?pr=43291

```
=========================== short test summary info ============================
FAILED tests/always/test_project_structure.py::TestProjectStructure::test_providers_modules_should_have_tests - AssertionError: Detect added tests in providers module - please remove the tests from OVERLOOKED_TESTS list above
assert equals failed
  set()                            set([
                                     'providers/tests/google/cloud
                                   /sensors/test_dataform.py',
                                   ])
= 1 failed, 12165 passed, 9445 skipped, 2 xfailed, 5 warnings in 571.47s (0:09:31) =

```

This was because the test was added in https://github.com/apache/airflow/pull/43055/