Improve the error message when a DAG tries to access the DB.
Previously it just gave a rather opaque error:

> module 'airflow.settings' has no attribute 'engine'

This improves that so that hopefully the user knows what is going on and isn't
left wondering if there's a bug in Airflow.