Bugfix: Allow clearing tasks with just ``dag_id`` and empty ``subdir``
Currently if we run the following command:

```
airflow tasks clear example_bash_operator --subdir ""
```

we get the following error:

```

Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 33, in <module>
    sys.exit(load_entry_point('apache-airflow', 'console_scripts', 'airflow')())
  File "/opt/airflow/airflow/__main__.py", line 40, in main
    args.func(args)
  File "/opt/airflow/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/opt/airflow/airflow/utils/cli.py", line 91, in wrapper
    return f(*args, **kwargs)
  File "/opt/airflow/airflow/cli/commands/task_command.py", line 454, in task_clear
    if args.dag_id and not args.subdir and not args.dag_regex and not args.task_regex:
  File "/opt/airflow/airflow/models/dag.py", line 1413, in clear_dags
    for dag in dags:
TypeError: 'DAG' object is not iterable
```

This is becase `DAG.clear_dags` expects an iterable.