Fix Amazon SES emailer signature
Amazon SES Had a wrong signature to become a mailer in Airflow
introduced in #18042. As the result setting SES emailer as
email backend resulted in:

```
TypeError: send_email() missing 1 required positional argument:
'html_content'
```

Fixes: #21671