Avoid trying to kill container when it did not succeed for Docker
When container cannot be created in Docker Operator and
exception is raised, the on_kill method attempts to kill the
container but since it is None, it fails with another exception

```
    self.cli.stop(self.container['Id'])
    TypeError: 'NoneType' object is not subscriptable
```

and the original exception is swallowed.

This PR avoids stopping the container if it has not been created.