Avoid chicken-egg situation with ES Provider and Airflow 2.1.1
This PR avoids chicken-egg situation; if Airflow 2.1.1 is released first
it will fail when using ES logging with following error:

```
Unable to load the config, contains a configuration error.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/logging/config.py", line 563, in configure
    handler = self.configure_handler(handlers[name])
  File "/usr/local/lib/python3.7/logging/config.py", line 736, in configure_handler
    result = factory(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'host_field'
```

This is because this will be added in soon to be released ES provider 2.0.1.

So `apache-airflow[elasticsearch]==2.1.1` needs `'apache-airflow-providers-elasticsearch>=2.0.1'`

We can avoid the need for this if we release the provider earlier. In which case we can close
this PR.