[AIRFLOW-3779] Don't install enum34 backport when not needed
https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-platform-specific-dependencies

Installing this in more recent versions causes a "AttributeError: module
'enum' has no attribute 'IntFlag'`" in re.py