Better error message when sqlite URL uses relative path (#36774)
When sqlite URL uses relative path, the error printed is quite
cryptic:

```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
```

This might easily happen for example when you are in a hurry and put
relative value in your AIRFLOW_HOME.

This PR checks if sql is relative and throws more appropriate and
explicit message what is wrong.

(cherry picked from commit 082055e23a38169a613f639296e144234f15d28c)