fix log_filename_template and dag_processer_manager_log_location
The default param for these causes jinja to error due to having
too many brackets.

Users who copy the default configuration will get the following
error on startup:
ValueError: Unable to configure handler 'processor':
expected token ':', got '}'