[AIRFLOW-3887] Downgrade dagre-d3 to 0.4.18
dagre-d3 v0.6.3 has a bug that causes this Javascript error when loading
the Graph View:

    TypeError: previousPaths.merge is not a function

The bug fix [1] has been merged to master, but hasn't been released to
npm yet. This change temporarily downgrades our version of dagre-d3
until dagre-d3 v0.6.4 is released [2]

I also fixed a bug I encountered in the `compile_assets.sh` where the
script would fail if the directory `airflow/www/static/dist/` exists but
is empty.

[1] https://github.com/dagrejs/dagre-d3/pull/350
[2] https://github.com/dagrejs/dagre-d3/blob/5450627790ff42012ef50cef6b0e220199ae4fbe/package.json#L3