Add missed import in the Trigger Rules example
An example of the Trigger Rules chapter raises the error while loading to UI:
Broken DAG: [/opt/airflow/dags/branch_without_trigger.py] Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/branch_without_trigger.py", line 16, in <module>
    @task.branch(task_id="branching")
NameError: name 'task' is not defined

It is needed to add the next import:
from airflow.decorators import task