Update secrets_manager.py
When a Secrets Manager call fails due to the secret not being accessible to the IAM principle, rather than just not existing, it reports:

botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the GetSecretValue operation: User: arn:aws:sts::xxx is not authorized to perform: secretsmanager:GetSecretValue on resource: yyy because no identity-based policy allows the secretsmanager:GetSecretValue action

For example, if a user wants to limit an environment to secrets that are tagged with a specific resource.  Today, this causes a failure with the Scheduler as an uncaught exception.  This PR addresses that condition, plus adds an additional catch for other exceptions that we're not aware of yet.