Add response migration for `consumed_asset_events` events field (#48940)
And, like I should have done in #48888, add tests this time.

The issue was caused by me misunderstanding how Cadwyn works, the
`instructions_to_migrate_to_previous_version` only affect the OpenAPI schema,
but since the change in this case results in an "invalid" model being
returned, we have to write our own migration for the data.

For those curious, the error without this migration function is:

> fastapi.exceptions.ResponseValidationError: 1 validation errors:
>  {'type': 'extra_forbidden', 'loc': ('response', 'dag_run', 'consumed_asset_events'), 'msg': 'Extra inputs are not permitted', 'input': []}