Allow using dag decorator without arguments
This allow using:

```python
@dag
def my_dag(): ...
```

Currently it fails with:

```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/tamara.fingerlin/airflow/dags_manning/syntax_examples/dependencies_examples.py", line 29, in <module>
    dependency_syntax()
TypeError: dag.<locals>.wrapper() missing 1 required positional argument: 'f'
```

so currently we need to use:

```python
@dag()
def my_dag(): ...
```